{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.webhook.enabled }}
{{- if and .Values.webhook.pdb .Values.webhook.pdb.enabled (gt (int .Values.webhook.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "slurm-operator.webhook.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
spec:
  {{- if ne .Values.webhook.pdb.maxUnavailable nil }}
  maxUnavailable: {{ .Values.webhook.pdb.maxUnavailable }}
  {{- else if ne .Values.webhook.pdb.minAvailable nil }}
  minAvailable: {{ .Values.webhook.pdb.minAvailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "slurm-operator.webhook.selectorLabels" . | nindent 6 }}
{{- end }}{{- /* if .Values.webhook.pdb && .Values.webhook.pdb.enabled && replicas > 1 */}}
{{- end }}{{- /* if .Values.webhook.enabled */}}
