{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.webhook.enabled }}
{{- $certNamespacedName := printf "%s/%s" (include "slurm-operator.namespace" .) .Values.certManager.secretName -}}
{{- $durationDays := int 3650 -}}
{{- $ca := genCA .Values.certManager.secretName $durationDays -}}
{{- if not .Values.certManager.enabled }}
{{- $cn := (include "slurm-operator.webhook.name" .) -}}
{{- $dnsList := list (printf "%s.%s" (include "slurm-operator.webhook.name" .) (include "slurm-operator.namespace" .)) (printf "%s.%s.svc" (include "slurm-operator.webhook.name" .) (include "slurm-operator.namespace" .)) -}}
{{- $cert := genSignedCert $cn nil $dnsList $durationDays $ca -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certManager.secretName }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}{{- /* if not .Values.certManager.enabled */}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "slurm-operator.webhook.name" . }}
  {{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ $certNamespacedName | quote }}
    cert-manager.io/inject-ca-from: {{ $certNamespacedName | quote }}
  {{- end }}{{- /* if .Values.certManager.enabled */}}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
webhooks:
  - name: accountings.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - accountings
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-accounting
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: controllers.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - controllers
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-controller
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: loginsets.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - loginsets
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-loginset
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: nodesets.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - nodesets
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-nodeset
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: restapis.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - restapis
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-restapi
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 10 }}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: tokens.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - tokens
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /validate-slinky-slurm-net-v1alpha1-token
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 10 }}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "slurm-operator.webhook.name" . }}
  {{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ $certNamespacedName | quote }}
    cert-manager.io/inject-ca-from: {{ $certNamespacedName | quote }}
  {{- end }}{{- /* if .Values.certManager.enabled */}}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
webhooks:
  - name: accountings.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - accountings
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-accounting
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: controllers.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - controllers
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-controller
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: loginsets.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - loginsets
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-loginset
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: nodesets.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - nodesets
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-nodeset
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: restapis.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - restapis
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-restapi
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
  - name: tokens.{{- include "slurm-operator.apiGroup" . }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - {{ include "slurm-operator.apiGroup" . }}
        apiVersions:
          - "*"
        resources:
          - tokens
        operations:
          - CREATE
          - UPDATE
        scope: Namespaced
    clientConfig:
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ $ca.Cert | b64enc | quote }}
      {{- end }}{{- /* if not .Values.certManager.enabled */}}
      service:
        namespace: {{ include "slurm-operator.namespace" . }}
        name: {{ include "slurm-operator.webhook.name" . }}
        path: /mutate-slinky-slurm-net-v1alpha1-token
    {{- with .Values.webhook.timeoutSeconds }}
    timeoutSeconds: {{ . }}
    {{- end }}{{- /* with .Values.webhook.timeoutSeconds */}}
    admissionReviewVersions:
      - v1
      - v1beta1
      - v1alpha1
    sideEffects: None
{{- end }}{{- /* if .Values.webhook.enabled */}}
