---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-accounting
  failurePolicy: Fail
  name: vaccounting.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accountings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-controller
  failurePolicy: Fail
  name: vcontroller.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - controllers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-loginset
  failurePolicy: Fail
  name: vloginset.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loginsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-nodeset
  failurePolicy: Fail
  name: vnodeset.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodesets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-restapi
  failurePolicy: Fail
  name: vrestapi.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - restapis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slinky-slurm-net-v1alpha1-token
  failurePolicy: Fail
  name: vtoken.kb.io
  rules:
  - apiGroups:
    - slinky.slurm.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tokens
  sideEffects: None
