{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and (index .Values "slurm-exporter" "enabled") (index .Values "slurm-exporter" "exporter" "enabled") }}
apiVersion: slinky.slurm.net/v1beta1
kind: Token
metadata:
  name: {{ include "slurm.fullname" . }}-exporter
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  jwtHs256KeyRef:
    {{- if .Values.jwtHs256KeyRef }}
    {{- toYaml .Values.jwtHs256KeyRef | nindent 4 }}
    {{- else }}
    name: {{ include "slurm.authJwtHs256Ref.name" . }}
    key: {{ include "slurm.authJwtHs256Ref.key" . }}
    {{- end }}{{- /* if .Values.jwtHs256KeyRef */}}
  username: exporter
  lifetime: 8766h # infinite
  refresh: true
  secretRef:
    name: {{ index .Values "slurm-exporter" "exporter" "secretName" }}
    key: auth-token
{{- end }}{{- /* if and slurm-exporter.enabled slurm-exporter.exporter.enabled */}}
